import ACTIVATION_INSTRUCTION from './ACTIVATION.md?raw'
import HOLIDAY_INSTRUCTION from './HOLIDAY.md?raw'
import CHAT_FIRST_MESSAGE from './CHAT.md?raw'

export const INSTRUCTIONS = [ACTIVATION_INSTRUCTION, HOLIDAY_INSTRUCTION, CHAT_FIRST_MESSAGE] 
  